In [ ]:
#This notebook assumes you already have spiksortingrecording populated. 

In [ ]:
#for testing whitened vs unwhitened. 
#want to have one loop that caluclates the whitened waveforms wi

In [26]:
%reload_ext autoreload
%autoreload 2

import os
import numpy as np
import datajoint as dj
import spyglass as nd
# ignore datajoint+jupyter async warnings
import warnings
warnings.simplefilter('ignore', category=DeprecationWarning)
warnings.simplefilter('ignore', category=ResourceWarning)

import spyglass.common as sgc

from spyglass.common import (Session, IntervalList,LabMember, LabTeam, Raw, Session, Nwbfile,
                            Electrode)#,SpikeSortingView)
import spyglass.spikesorting as ss


# from spyglass.spikesorting import (SortGroup, 
#                                     SortInterval,
#                                     SpikeSortingPreprocessingParameters,
#                                     SpikeSortingRecording, 
#                                     SpikeSorterParameters,
#                                     SpikeSortingRecordingSelection,
#                                     ArtifactDetectionParameters, ArtifactDetectionSelection,
#                                     ArtifactRemovedIntervalList, ArtifactDetection,
#                                       SpikeSortingSelection, SpikeSorting,CuratedSpikeSortingSelection,
#                                   CuratedSpikeSorting)#,SpikeSortingView)
# # from spyglass.figurl_views import SpikeSortingView

In [2]:
os.environ['SPYGLASS_BASE_DIR'] = "/stelmo/nwb/"
os.environ['SPYGLASS_RECORDING_DIR'] = "/stelmo/nwb/recording"
os.environ['SPYGLASS_SORTING_DIR'] = "/stelmo/nwb/sorting"
os.environ['SPYGLASS_WAVEFORMS_DIR'] = "/stelmo/nwb/waveforms"
os.environ['SPYGLASS_TEMP_DIR'] = "/stelmo/nwb/tmp"
os.environ['KACHERY_DAEMON_HOST'] = "typhoon"
os.environ['KACHERY_DAEMON_PORT'] = "14747"
os.environ['KACHERY_STORAGE_DIR'] = "/stelmo/nwb/kachery-storage"
os.environ['KACHERY_TEMP_DIR'] = "/stelmo/nwb/tmp"
os.environ['FIGURL_CHANNEL'] = "franklab2"
os.environ['DJ_SUPPORT_FILEPATH_MANAGEMENT'] = "TRUE"
dj.config["enable_python_native_blobs"] = True

In [3]:
nwb_file_name =  'senor20201030_.nwb'
sort_group_id = 28

tetrode = False
if tetrode:
    sort_interval_name= 'runs_noPrePostTrialTimes raw data valid times'
else: 
    sort_interval_name= 'sleeps_runs_noPrePostTrialTimes raw data valid times'

# tetrode = True 

In [118]:
(ss.Curation() & {'nwb_file_name' : nwb_file_name, 'sorter':'mountainsort4'})#, 'sorter_params_name':'franklab_tetrode_hippocampus_30KHz'}) #& {'preproc_params_name':'default'})

*curation_id   *nwb_file_name *sort_group_id *sort_interval *preproc_param *team_name    *sorter        *sorter_params *artifact_remo parent_curatio curation_l merge_grou quality_me description    time_of_creati
+------------+ +------------+ +------------+ +------------+ +------------+ +-----------+ +------------+ +------------+ +------------+ +------------+ +--------+ +--------+ +--------+ +------------+ +------------+
0              senor20201030_ 8              runs_noPrePost franklab_tetro ac_em_xs      mountainsort4  franklab_tetro senor20201030_ -1             =BLOB=     =BLOB=     =BLOB=                    1655319635    
1              senor20201030_ 8              runs_noPrePost franklab_tetro ac_em_xs      mountainsort4  franklab_tetro senor20201030_ 0              =BLOB=     =BLOB=     =BLOB=     auto curated   1655321170    
0              senor20201030_ 24             sleeps_runs_no default        ac_em_xs      mountainsort4  franklab_probe senor20201030_ -1             =BLOB=     =BLOB=     =BLOB=                    1656006827    
1              senor20201030_ 24             sleeps_runs_no default        ac_em_xs      mountainsort4  franklab_probe senor20201030_ 0              =BLOB=     =BLOB=     =BLOB=     auto curated   1656010692    
2              senor20201030_ 24             sleeps_runs_no default        ac_em_xs      mountainsort4  franklab_probe senor20201030_ 1              =BLOB=     =BLOB=     =BLOB=     auto curated   1656022801    
3              senor20201030_ 24             sleeps_runs_no default        ac_em_xs      mountainsort4  franklab_probe senor20201030_ 0              =BLOB=     =BLOB=     =BLOB=     auto curated   1656104356    
4              senor20201030_ 24             sleeps_runs_no default        ac_em_xs      mountainsort4  franklab_probe senor20201030_ 0              =BLOB=     =BLOB=     =BLOB=     auto curated   1656112623    
0              senor20201030_ 27             sleeps_runs_no default        ac_em_xs      mountainsort4  franklab_probe senor20201030_ -1             =BLOB=     =BLOB=     =BLOB=                    1655180987    
1              senor20201030_ 27             sleeps_runs_no default        ac_em_xs      mountainsort4  franklab_probe senor20201030_ 0              =BLOB=     =BLOB=     =BLOB=     auto curated   1655219461    
0              senor20201030_ 28             sleeps_runs_no default        ac_em_xs      mountainsort4  franklab_probe senor20201030_ -1             =BLOB=     =BLOB=     =BLOB=                    1655506445    
1              senor20201030_ 28             sleeps_runs_no default        ac_em_xs      mountainsort4  franklab_probe senor20201030_ 0              =BLOB=     =BLOB=     =BLOB=     auto curated   1655510118    
2              senor20201030_ 28             sleeps_runs_no default        ac_em_xs      mountainsort4  franklab_probe senor20201030_ 0              =BLOB=     =BLOB=     =BLOB=     auto curated   1655510141    
   ...
 (Total: 20)

In [43]:
(ss.SpikeSortingRecordingSelection() & {'team_name':'ac_em_xs','nwb_file_name':'wilbur20210406_.nwb'})#.fetch()

*nwb_file_name *sort_group_id *sort_interval *preproc_param *team_name    interval_list_
+------------+ +------------+ +------------+ +------------+ +-----------+ +------------+
wilbur20210406 25             02_r1_noPrePos default        ac_em_xs      02_r1 noPrePos
 (Total: 1)

In [51]:
nwb_file_name = 'wilbur20210406_.nwb'
sort_interval_name = '02_r1_noPrePostTrialTimes_test_100s'
sort_group_id = 25

In [55]:
#making sure your spikesortingrecording table has an entry. if not, can adapt the commented code 

(ss.SpikeSortingRecordingSelection() & {'nwb_file_name' : nwb_file_name, 'sort_interval_name' : sort_interval_name, 'sort_group_id':sort_group_id})

#if not yet populated, can implement the 
# key = dict()
# key['nwb_file_name'] = nwb_file_name
# key['sort_group_id'] = sort_group_id
# key['sort_interval_name'] = sort_interval_name
# # key['preproc_params_name'] = 'franklab_tetrode_hippocampus'
# # key['interval_list_name'] = 'r1_r2_r3'
# # key['team_name'] = 'mcoulter section'

# ssr_key1 = key

# SpikeSortingRecordingSelection.insert1(ssr_key1, skip_duplicates=True,)
ss.SpikeSortingRecording.populate([(ss.SpikeSortingRecordingSelection & {'nwb_file_name' : nwb_file_name, 'sort_interval_name' : sort_interval_name, 'sort_group_id':sort_group_id}).proj()])

In [56]:
ss.SpikeSortingRecording& {'nwb_file_name' : nwb_file_name, 'sort_interval_name' : sort_interval_name, 'sort_group_id':sort_group_id}

*nwb_file_name *sort_group_id *sort_interval *preproc_param *team_name    recording_path sort_interval_
+------------+ +------------+ +------------+ +------------+ +-----------+ +------------+ +------------+
wilbur20210406 25             02_r1_noPrePos default        ac_em_xs      /stelmo/nwb/re wilbur20210406
 (Total: 1)

# artifact detection 

In [57]:
artifact_params = 'ampl_2000_z_30_prop_075_1ms'

In [60]:
#this will popualte the artifact detection table, will print out what it found. 
artifact_key = (ss.SpikeSortingRecordingSelection() &  {'nwb_file_name' : nwb_file_name} & 
                     {'sort_interval_name' : sort_interval_name} & {'sort_group_id' : sort_group_id}).fetch1('KEY')
# artifact_key['artifact_params_name'] = art_param_list[2][0]
artifact_key['artifact_params_name'] = artifact_params
artifact_key

ss.ArtifactDetectionSelection.insert1(artifact_key, skip_duplicates=True)
ss.ArtifactDetectionSelection & artifact_key
ss.ArtifactDetection.populate([(ss.ArtifactDetectionSelection & artifact_key).proj()])
ss.ArtifactDetection & artifact_key

Versions are not the same. This might lead to errors. Use  spikeinterface version 0.95.0.dev0
No artifacts detected.


*nwb_file_name *sort_group_id *sort_interval *preproc_param *team_name    *artifact_para artifact_t artifact_r artifact_remov
+------------+ +------------+ +------------+ +------------+ +-----------+ +------------+ +--------+ +--------+ +------------+
wilbur20210406 25             02_r1_noPrePos default        ac_em_xs      ampl_2000_z_30 =BLOB=     =BLOB=     wilbur20210406
 (Total: 1)

In [61]:
tetrode=False

In [13]:
#just making sure this downstream table has been filled 
ss.ArtifactRemovedIntervalList() &  artifact_key

*artifact_remo nwb_file_name  sort_group_id  sort_interval_ preproc_params team_name     artifact_param artifact_r artifact_t
+------------+ +------------+ +------------+ +------------+ +------------+ +-----------+ +------------+ +--------+ +--------+
senor20201030_ senor20201030_ 24             sleeps_runs_no default        ac_em_xs      ampl_2000_z_30 =BLOB=     =BLOB=    
 (Total: 1)

In [35]:
(SpikeSorterParameters() &{'sorter':'mountainsort4'}).fetch()

array([('mountainsort4', 'default', {'detect_sign': -1, 'adjacency_radius': -1, 'freq_min': 300, 'freq_max': 6000, 'filter': True, 'whiten': True, 'num_workers': 1, 'clip_size': 50, 'detect_threshold': 3, 'detect_interval': 10}),
       ('mountainsort4', 'franklab_probe_ctx_30KHz', {'detect_sign': -1, 'adjacency_radius': 100, 'freq_min': 300, 'freq_max': 6000, 'filter': False, 'whiten': True, 'num_workers': 1, 'clip_size': 40, 'detect_threshold': 3, 'detect_interval': 10}),
       ('mountainsort4', 'franklab_probe_ctx_30KHz_115rad', {'detect_sign': -1, 'adjacency_radius': 115, 'freq_min': 300, 'freq_max': 6000, 'filter': False, 'whiten': True, 'num_workers': 1, 'clip_size': 40, 'detect_threshold': 3, 'detect_interval': 10}),
       ('mountainsort4', 'franklab_tetrode_30KHz', {'detect_sign': -1, 'adjacency_radius': 100, 'freq_min': 300, 'freq_max': 6000, 'filter': False, 'whiten': True, 'num_workers': 4, 'clip_size': 30, 'detect_threshold': 3, 'detect_interval': 10}),
       ('mountains

# populate SpikeSorting(+Selection) tables

In [64]:
if tetrode: 
    spike_sorting_params_name='franklab_tetrode_hippocampus_30KHz'
else: 
    spike_sorting_params_name='franklab_probe_ctx_30KHz'#_115rad'


artifact_intervals = (ss.ArtifactDetection() & {'nwb_file_name' : nwb_file_name} 
                          & {'artifact_params_name': artifact_params}
                          & {'sort_interval_name' : sort_interval_name} & {'sort_group_id' : sort_group_id}
                         ).fetch('artifact_removed_interval_list_name')[0]
    
sorting_key = (ss.SpikeSortingRecordingSelection() &  {'nwb_file_name' : nwb_file_name} & 
                 {'sort_interval_name' : sort_interval_name} & {'sort_group_id' : sort_group_id}).fetch1('KEY')    
sorting_key['sorter'] = 'mountainsort4'
sorting_key['sorter_params_name'] = spike_sorting_params_name
sorting_key['artifact_removed_interval_list_name'] = artifact_intervals

ss.SpikeSortingSelection.insert1(sorting_key, skip_duplicates=True)

ss.SpikeSortingSelection & sorting_key

*nwb_file_name *sort_group_id *sort_interval *preproc_param *team_name    *sorter        *sorter_params *artifact_remo import_path   
+------------+ +------------+ +------------+ +------------+ +-----------+ +------------+ +------------+ +------------+ +------------+
wilbur20210406 25             02_r1_noPrePos default        ac_em_xs      mountainsort4  franklab_probe wilbur20210406               
 (Total: 1)

In [65]:
%%time

ss.SpikeSorting.populate([(ss.SpikeSortingSelection & sorting_key).proj()])

ss.SpikeSorting & sorting_key

Versions are not the same. This might lead to errors. Use  spikeinterface version 0.95.0.dev0
Running spike sorting on {'nwb_file_name': 'wilbur20210406_.nwb', 'sort_group_id': 25, 'sort_interval_name': '02_r1_noPrePostTrialTimes_test_100s', 'preproc_params_name': 'default', 'team_name': 'ac_em_xs', 'sorter': 'mountainsort4', 'sorter_params_name': 'franklab_probe_ctx_30KHz', 'artifact_removed_interval_list_name': 'wilbur20210406_.nwb_02_r1_noPrePostTrialTimes_test_100s_25_default_ampl_2000_z_30_prop_075_1ms_artifact_removed_valid_times'}...
Mountainsort4 use the OLD spikeextractors mapped with NewToOldRecording


/home/emonroe/miniconda2/envs/spyglass/lib/python3.8/site-packages/neo/io/nixio.py:57: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  MIN_NIX_VER = Version("1.5.0")
/home/emonroe/miniconda2/envs/spyglass/lib/python3.8/site-packages/neo/io/neomatlabio.py:30: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if version.LooseVersion(scipy.version.version) < '0.12.0':
/home/emonroe/miniconda2/envs/spyglass/lib/python3.8/site-packages/setuptools/_distutils/version.py:351: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  other = LooseVersion(other)
/home/emonroe/miniconda2/envs/spyglass/lib/python3.8/site-packages/neo/io/nixio.py:57: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  MIN_NIX_VER = Version("1.5.0")
/home/emonroe/miniconda2/envs/spyglass/lib/python3.8/site-packages/neo/io/neomatlabio.py:30: Deprec

Saving sorting results...


/home/emonroe/miniconda2/envs/spyglass/lib/python3.8/site-packages/spikeinterface/core/basesorting.py:119: UserWarning: The registered recording will not be persistent on disk, but only available in memory
  warnings.warn(
/home/emonroe/miniconda2/envs/spyglass/lib/python3.8/tempfile.py:818: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/stelmo/nwb/tmp/tmplsn5hvey'>
  _warnings.warn(warn_message, ResourceWarning)


CPU times: user 14.6 s, sys: 26.6 s, total: 41.2 s
Wall time: 50.3 s


*nwb_file_name *sort_group_id *sort_interval *preproc_param *team_name    *sorter        *sorter_params *artifact_remo sorting_path   time_of_sort  
+------------+ +------------+ +------------+ +------------+ +-----------+ +------------+ +------------+ +------------+ +------------+ +------------+
wilbur20210406 25             02_r1_noPrePos default        ac_em_xs      mountainsort4  franklab_probe wilbur20210406 /stelmo/nwb/so 1656450156    
 (Total: 1)

In [17]:
ss.SpikeSorting & sorting_key

*nwb_file_name *sort_group_id *sort_interval *preproc_param *team_name    *sorter        *sorter_params *artifact_remo sorting_path   time_of_sort  
+------------+ +------------+ +------------+ +------------+ +-----------+ +------------+ +------------+ +------------+ +------------+ +------------+
senor20201030_ 24             sleeps_runs_no default        ac_em_xs      mountainsort4  franklab_probe senor20201030_ /stelmo/nwb/so 1654840942    
 (Total: 1)

# Curation

In [67]:
#grt a mySQL error here even though it adds the entry to the table, whats going on there? 
curation_key = sorting_key.copy()
curation_key.update({'curation_id' : 0})

# ss.Curation.insert_curation(curation_key)

ss.Curation() & curation_key

*curation_id   *nwb_file_name *sort_group_id *sort_interval *preproc_param *team_name    *sorter        *sorter_params *artifact_remo parent_curatio curation_l merge_grou quality_me description    time_of_creati
+------------+ +------------+ +------------+ +------------+ +------------+ +-----------+ +------------+ +------------+ +------------+ +------------+ +--------+ +--------+ +--------+ +------------+ +------------+
0              wilbur20210406 25             02_r1_noPrePos default        ac_em_xs      mountainsort4  franklab_probe wilbur20210406 -1             =BLOB=     =BLOB=     =BLOB=                    1656450181    
 (Total: 1)

## waveforms

In [68]:
waveform_key_whitened = curation_key.copy()
#deep_copy? 
waveform_params_name = 'default_whitened'
waveform_key_whitened.update({'waveform_params_name': 'default_whitened'})
ss.WaveformSelection.insert1(waveform_key_whitened, skip_duplicates=True)
ss.Waveforms.populate([(ss.WaveformSelection & waveform_key_whitened).proj()])
ss.Waveforms() & waveform_key_whitened




Versions are not the same. This might lead to errors. Use  spikeinterface version 0.95.0.dev0
Extracting waveforms...
Setting 'return_scaled' to False


/home/emonroe/miniconda2/envs/spyglass/lib/python3.8/multiprocessing/popen_fork.py:70: ResourceWarning: unclosed socket <zmq.Socket(zmq.PUSH) at 0x7f13f07d16a0>
  self.pid = os.fork()
/home/emonroe/miniconda2/envs/spyglass/lib/python3.8/multiprocessing/popen_fork.py:70: ResourceWarning: unclosed socket <zmq.Socket(zmq.PUSH) at 0x7f05ff13ee20>
  self.pid = os.fork()
/home/emonroe/miniconda2/envs/spyglass/lib/python3.8/multiprocessing/popen_fork.py:70: ResourceWarning: unclosed socket <zmq.Socket(zmq.PUSH) at 0x7f131cd45040>
  self.pid = os.fork()
/home/emonroe/miniconda2/envs/spyglass/lib/python3.8/site-packages/h5py/_hl/dataset.py:541: DeprecationWarning: Passing None into shape arguments as an alias for () is deprecated.
  arr = numpy.ndarray(selection.mshape, dtype=new_dtype)
/home/emonroe/miniconda2/envs/spyglass/lib/python3.8/site-packages/hdmf/spec/namespace.py:532: UserWarning: Ignoring cached namespace 'hdmf-common' version 1.5.0 because version 1.5.1 is already loaded.
  warn("

Writing new NWB file wilbur20210406_SW05XH8QIM.nwb


/home/emonroe/miniconda2/envs/spyglass/lib/python3.8/site-packages/h5py/_hl/dataset.py:541: DeprecationWarning: Passing None into shape arguments as an alias for () is deprecated.
  arr = numpy.ndarray(selection.mshape, dtype=new_dtype)
/home/emonroe/miniconda2/envs/spyglass/lib/python3.8/site-packages/hdmf/build/objectmapper.py:256: DtypeConversionWarning: Spec 'Units/spike_times': Value with data type int64 is being converted to data type float64 as specified.
  warnings.warn(full_warning_msg, DtypeConversionWarning)
/home/emonroe/miniconda2/envs/spyglass/lib/python3.8/site-packages/datajoint/hash.py:39: ResourceWarning: unclosed file <_io.BufferedReader name='/stelmo/nwb/analysis/wilbur20210406_SW05XH8QIM.nwb'>
  return uuid_from_stream(Path(filepath).open("rb"), init_string=init_string)
/home/emonroe/miniconda2/envs/spyglass/lib/python3.8/site-packages/datajoint/external.py:276: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this 

*curation_id   *nwb_file_name *sort_group_id *sort_interval *preproc_param *team_name    *sorter        *sorter_params *artifact_remo *waveform_para waveform_extra analysis_file_ waveforms_obje
+------------+ +------------+ +------------+ +------------+ +------------+ +-----------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+
0              wilbur20210406 25             02_r1_noPrePos default        ac_em_xs      mountainsort4  franklab_probe wilbur20210406 default_whiten /stelmo/nwb/wa wilbur20210406 8b1afd3b-5c1b-
 (Total: 1)

In [69]:
waveform_key_whitened

{'nwb_file_name': 'wilbur20210406_.nwb',
 'sort_group_id': 25,
 'sort_interval_name': '02_r1_noPrePostTrialTimes_test_100s',
 'preproc_params_name': 'default',
 'team_name': 'ac_em_xs',
 'sorter': 'mountainsort4',
 'sorter_params_name': 'franklab_probe_ctx_30KHz',
 'artifact_removed_interval_list_name': 'wilbur20210406_.nwb_02_r1_noPrePostTrialTimes_test_100s_25_default_ampl_2000_z_30_prop_075_1ms_artifact_removed_valid_times',
 'curation_id': 0,
 'waveform_params_name': 'default_whitened'}

In [32]:
spike_amplitude_dict = dict().fromkeys((ss.SpikeSorting() &  waveform_key_whitened).fetch('sort_group_id'))

key=waveform_key_whitened

In [30]:
spike_amplitude_dict 

{28: None}

In [70]:
key

{'nwb_file_name': 'senor20201030_.nwb',
 'sort_group_id': 28,
 'sort_interval_name': 'sleeps_runs_noPrePostTrialTimes raw data valid times',
 'preproc_params_name': 'default',
 'team_name': 'ac_em_xs',
 'sorter': 'mountainsort4',
 'sorter_params_name': 'franklab_probe_ctx_30KHz',
 'artifact_removed_interval_list_name': 'senor20201030_.nwb_sleeps_runs_noPrePostTrialTimes raw data valid times_28_default_ampl_2000_z_30_prop_075_1ms_artifact_removed_valid_times',
 'waveform_params_name': 'default_whitened'}

In [71]:
spike_times

[array([      790,       894,      1100, ..., 716113963, 716114165,
        716115691]),
 array([     3182,      9137,     10315, ..., 716098677, 716104094,
        716113175]),
 array([    51007,     57207,     66495, ..., 715977088, 716012961,
        716020677]),
 array([       43,       142,      2219, ..., 716113014, 716113410,
        716115217]),
 array([     3163,      5461,      6593, ..., 716114222, 716114365,
        716114592]),
 array([     3935,      4449,      8522, ..., 716112211, 716112632,
        716115424]),
 array([      815,      4819,      7975, ..., 716110126, 716114135,
        716114423]),
 array([      538,      2049,      2856, ..., 716111472, 716112275,
        716112885]),
 array([    50359,     70674,     74613, ..., 715678708, 715704932,
        715719962]),
 array([    32981,     41991,     50285, ..., 715988322, 716002403,
        716109833]),
 array([     3660,      5590,      7341, ..., 715903903, 715910172,
        716012050]),
 array([    20808,   

In [38]:
for key in (ss.SpikeSorting() & key).fetch('KEY'):
    key['waveform_params_name'] = waveform_params_name
    we = (ss.Waveforms & key).load_waveforms(key)
    waveforms_w_ind = [we.get_waveforms(unit,with_index=True) for unit in we.sorting.get_unit_ids()]
    spike_waveforms = [np.swapaxes(waveforms[0], 0, 2) for waveforms in waveforms_w_ind]
    spike_inds = [np.array(list(zip(*waveforms[1])),dtype=np.int64)[0] for waveforms in waveforms_w_ind]
    spike_times = [we.sorting.get_unit_spike_train(unit_id=unit) for unit in we.sorting.get_unit_ids()]
    selected_spike_times = [spike_times[unit][inds] for unit, inds in enumerate(spike_inds)]
    n_clusters = len(we.sorting.get_unit_ids())
    n_channels = len(we.recording.get_channel_ids())
    spike_waveform_arr = make_waveform_arr(spike_waveforms, n_clusters, n_channels, 28)
    spike_times_arr = make_spike_times_arr(selected_spike_times, n_clusters)
    spike_window_min = np.nanmin(spike_waveform_arr[:,:,14-3:14+3,:], axis=2)
    rec_timestamps = we.recording.get_times()
    samp_freq = we.recording.get_sampling_frequency()
    spike_amplitude_dict[key['sort_group_id']] = {'spike_times' : spike_times_arr,
                                                  'spike_amplitude' : spike_window_min,
                                                  'samp_freq' : samp_freq,
                                                  'timestamps' : rec_timestamps}

NameError: name 'spike_times_arr' is not defined

## Metrics

In [60]:
# (ss.MetricParameters()).fetch()# &{'metric_params_name':'franklab_default'}).fetch1('metric_params')

In [21]:
EM_test = ('EM_pos_peak_offset_min_spikes', {'snr': {'peak_sign': 'neg', 'num_chunks_per_segment': 20, 'chunk_size': 10000, 'seed': 0},
                                         'isi_violation': {'isi_threshold_ms': 1.5, 'min_isi_ms': 0.0},
                                         'nn_isolation': {'max_spikes_for_nn': 1000, 'n_neighbors': 5, 'n_components': 7, 'radius_um': 100, 'seed': 0, 'min_spikes_for_nn': 10},
                                         'nn_noise_overlap': {'max_spikes_for_nn': 1000, 'n_neighbors': 5, 'n_components': 7, 'radius_um': 100, 'seed': 0,'min_spikes_for_nn': 10}, 
                                         'peak_offset': {'peak_sign': 'pos'}})

In [80]:
EM_test

('EM_peak_offset_min_spikes',
 {'snr': {'peak_sign': 'neg',
   'num_chunks_per_segment': 20,
   'chunk_size': 10000,
   'seed': 0},
  'isi_violation': {'isi_threshold_ms': 1.5, 'min_isi_ms': 0.0},
  'nn_isolation': {'max_spikes_for_nn': 1000,
   'n_neighbors': 5,
   'n_components': 7,
   'radius_um': 100,
   'seed': 0,
   'min_spikes_for_nn': 10},
  'nn_noise_overlap': {'max_spikes_for_nn': 1000,
   'n_neighbors': 5,
   'n_components': 7,
   'radius_um': 100,
   'seed': 0,
   'min_spikes_for_nn': 10},
  'peak_offset': {'peak_sign': 'neg'}})

In [22]:
ss.MetricParameters().insert1(EM_test)

In [85]:
# ss.MetricParameters().fetch()

array([('DPG_just_peak_offset', {'peak_offset': {'peak_sign': 'neg'}}),
       ('DPG_no_peak_offset', {'snr': {'peak_sign': 'neg', 'num_chunks_per_segment': 20, 'chunk_size': 10000, 'seed': 0}, 'isi_violation': {'isi_threshold_ms': 1.5, 'min_isi_ms': 0.0}, 'nn_isolation': {'max_spikes_for_nn': 1000, 'n_neighbors': 5, 'n_components': 7, 'radius_um': 100, 'seed': 0}, 'nn_noise_overlap': {'max_spikes_for_nn': 1000, 'n_neighbors': 5, 'n_components': 7, 'radius_um': 100, 'seed': 0}}),
       ('DPG_peak_offset', {'snr': {'peak_sign': 'neg', 'num_chunks_per_segment': 20, 'chunk_size': 10000, 'seed': 0}, 'isi_violation': {'isi_threshold_ms': 1.5, 'min_isi_ms': 0.0}, 'nn_isolation': {'max_spikes_for_nn': 1000, 'n_neighbors': 5, 'n_components': 7, 'radius_um': 100, 'seed': 0}, 'nn_noise_overlap': {'max_spikes_for_nn': 1000, 'n_neighbors': 5, 'n_components': 7, 'radius_um': 100, 'seed': 0}, 'peak_offset': {'peak_sign': 'neg'}}),
       ('DPG_test_05_06_22', {'snr': {'peak_sign': 'neg', 'num_chunk

In [72]:
# metrics_params_whitened = 'JG_DG_no_peak_offset_min_spikes'
metrics_params_whitened = 'EM_pos_peak_offset_min_spikes'
metrics_key_whitened = waveform_key_whitened.copy()
metrics_key_whitened['metric_params_name'] =  metrics_params_whitened

ss.MetricSelection.insert1(metrics_key_whitened, skip_duplicates=True)
ss.QualityMetrics.populate([(ss.MetricSelection & metrics_key_whitened).proj()])


Computed all metrics: {'snr': {1: 3.0330479079150674, 2: 3.0247999230139477, 3: 3.0230352584108156, 4: 3.0263487564143676, 5: 3.02072063086951, 6: 3.0136545995663577, 7: 3.0113150626372103, 8: 3.0180641299064415, 9: 3.0177865855309056, 10: 3.0194414961210856, 11: 3.0294449985594856, 12: 3.1328288031339198, 13: 5.221381338556533, 14: 3.127428515499036, 15: 8.339809374664096, 16: 8.507904827356018, 17: 3.1904643102585064, 18: 3.0707259840898584, 19: 3.0790965514873854, 20: 19.500944826086776, 21: 3.028610338663013, 22: 3.1683766817081684, 23: 9.505130045124506, 24: 3.0349881781287755, 25: 3.0637013058889884, 26: 3.0494095308989175, 27: 3.068719541150113, 28: 3.164408651520765, 29: 3.0393117028882544, 30: 7.672981114727981, 31: 3.2884204777405635, 32: 3.0883915862735947, 33: 3.0758183270075867, 34: 3.1413992566255837, 35: 3.123976711295598, 36: 7.2892789930230615, 37: 3.0792006490860118, 38: 3.066052772699231, 39: 3.056558140326755}, 'isi_violation': {'1': 0.006462035541195477, '2': 0.011

/home/emonroe/miniconda2/envs/spyglass/lib/python3.8/site-packages/h5py/_hl/dataset.py:541: DeprecationWarning: Passing None into shape arguments as an alias for () is deprecated.
  arr = numpy.ndarray(selection.mshape, dtype=new_dtype)
/home/emonroe/miniconda2/envs/spyglass/lib/python3.8/site-packages/hdmf/spec/namespace.py:532: UserWarning: Ignoring cached namespace 'hdmf-common' version 1.5.0 because version 1.5.1 is already loaded.
  warn("Ignoring cached namespace '%s' version %s because version %s is already loaded."
/home/emonroe/miniconda2/envs/spyglass/lib/python3.8/site-packages/hdmf/spec/namespace.py:532: UserWarning: Ignoring cached namespace 'core' version 2.3.0 because version 2.4.0 is already loaded.
  warn("Ignoring cached namespace '%s' version %s because version %s is already loaded."
/home/emonroe/miniconda2/envs/spyglass/lib/python3.8/site-packages/hdmf/spec/namespace.py:532: UserWarning: Ignoring cached namespace 'hdmf-experimental' version 0.1.0 because version 0.

Writing new NWB file wilbur20210406_EQDN0FNCP4.nwb


/home/emonroe/miniconda2/envs/spyglass/lib/python3.8/site-packages/h5py/_hl/dataset.py:541: DeprecationWarning: Passing None into shape arguments as an alias for () is deprecated.
  arr = numpy.ndarray(selection.mshape, dtype=new_dtype)


Adding metric snr : {1: 3.0330479079150674, 2: 3.0247999230139477, 3: 3.0230352584108156, 4: 3.0263487564143676, 5: 3.02072063086951, 6: 3.0136545995663577, 7: 3.0113150626372103, 8: 3.0180641299064415, 9: 3.0177865855309056, 10: 3.0194414961210856, 11: 3.0294449985594856, 12: 3.1328288031339198, 13: 5.221381338556533, 14: 3.127428515499036, 15: 8.339809374664096, 16: 8.507904827356018, 17: 3.1904643102585064, 18: 3.0707259840898584, 19: 3.0790965514873854, 20: 19.500944826086776, 21: 3.028610338663013, 22: 3.1683766817081684, 23: 9.505130045124506, 24: 3.0349881781287755, 25: 3.0637013058889884, 26: 3.0494095308989175, 27: 3.068719541150113, 28: 3.164408651520765, 29: 3.0393117028882544, 30: 7.672981114727981, 31: 3.2884204777405635, 32: 3.0883915862735947, 33: 3.0758183270075867, 34: 3.1413992566255837, 35: 3.123976711295598, 36: 7.2892789930230615, 37: 3.0792006490860118, 38: 3.066052772699231, 39: 3.056558140326755}
Adding metric isi_violation : {'1': 0.006462035541195477, '2': 0.0

/home/emonroe/miniconda2/envs/spyglass/lib/python3.8/site-packages/datajoint/hash.py:39: ResourceWarning: unclosed file <_io.BufferedReader name='/stelmo/nwb/analysis/wilbur20210406_EQDN0FNCP4.nwb'>
  return uuid_from_stream(Path(filepath).open("rb"), init_string=init_string)
/home/emonroe/miniconda2/envs/spyglass/lib/python3.8/site-packages/datajoint/external.py:276: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if check_hash:


In [10]:
# ss.QualityMetrics() & {'nwb_file_name':nwb_file_name,'sort_group_id': 24}
(ss.QualityMetrics() & metrics_key_whitened).fetch()



array([],
      dtype=[('curation_id', '<i8'), ('nwb_file_name', 'O'), ('sort_group_id', '<i8'), ('sort_interval_name', 'O'), ('preproc_params_name', 'O'), ('team_name', 'O'), ('sorter', 'O'), ('sorter_params_name', 'O'), ('artifact_removed_interval_list_name', 'O'), ('waveform_params_name', 'O'), ('metric_params_name', 'O'), ('quality_metrics_path', 'O'), ('analysis_file_name', 'O'), ('object_id', 'O')])

In [102]:
# EM_autoc = {'auto_curation_params_name' : 'EM_peak_offset',
#             'merge_params' : {},
#             'label_params' : {
#                    'peak_offset' : ['>',2,['noise','reject']],
#                     'peak_offset' : ['<',-2,['noise','reject']]}
            
# (ss.AutomaticCurationParameters() & {'auto_curation_params_name':'EM_probe_autocuration_params'}).fetch()
EM_Autoc = ({'auto_curation_params_name' : 'EM_probe_autocuration_params_test2',
            'merge_params' : {},
            'label_params' : {'nn_noise_overlap': ['>', 0.03, ['noise', 'reject']],
                                      'isi_violation': ['>', 0.0025, ['noise', 'reject']],
                                      'snr': ['<', 3, ['noise', 'reject']],
                                      'nn_isolation': ['<', 0.95, ['noise', 'reject']],
                                      'peak_offset': ['>', 2, ['noise', 'reject']]}})

In [103]:
EM_Autoc
ss.AutomaticCurationParameters().insert1(EM_Autoc)

In [28]:
(ss.Curation & auto_curation_id).fetch('quality_metrics')

array([{'snr': {'1': 3.095255184041835, '2': 3.1196099384592006, '3': 7.279089856404802, '4': 5.199349897432001, '5': 13.066384899347245, '6': 3.2665962248368112, '7': 3.650265264876104, '8': 25.551856854132726, '9': 9.734040706336277, '10': 12.167550882920345, '11': 4.1364781412281415, '12': 11.030608376608377, '13': 19.303564659064662, '14': 11.030608376608377, '15': 44.12243350643351, '16': 30.33417303567304, '17': 9.651782329532331, '18': 9.651782329532331, '19': 2.433510176584069, '20': 5.515304188304189, '21': 1.2167550882920346, '22': 3.3672123059738412, '23': 4.547539377146998, '24': 7.858478962881714, '25': 3.3679195555207344, '26': 3.488968278761777, '27': 7.408524902225274, '28': 3.704262451112637, '29': 6.173770751854395, '30': 13.582295654079669, '31': 17.286558105192306, '32': 20.990820556304943, '33': 5.035459285453077, '34': 3.7765944640898073, '35': 1.4819944351605252, '36': 11.329783392269421, '37': 6.294324106816346, '38': 15.106377856359229, '39': 8.812053749542883,

## Autocuration 

In [73]:
#do first round of autocuration using the whitened waveforms. 
#then grab the key from this to update for second round. 

if tetrode: 
    auto_curation_params_name_whitened ='mike_noise_isi_isolation'
else:
    # auto_curation_params_name_whitened = 'EM_probe_autocuration_params'
    auto_curation_params_name_whitened ='EM_probe_autocuration_params_test2'
    
autocuration_key_whitened = metrics_key_whitened.copy()
autocuration_key_whitened['auto_curation_params_name'] = auto_curation_params_name_whitened

ss.AutomaticCurationSelection.insert1(autocuration_key_whitened, skip_duplicates=True)
ss.AutomaticCuration.populate([(ss.AutomaticCurationSelection & autocuration_key_whitened).proj()])

auto_curation_id = (ss.AutomaticCuration & autocuration_key_whitened).fetch1('auto_curation_key')
auto_curation_out_key = (ss.Curation & auto_curation_id).fetch1("KEY")


In [74]:
auto_curation_id2 = (ss.AutomaticCuration & autocuration_key_whitened).fetch1('auto_curation_key')
key2  = (ss.Curation & auto_curation_id2).fetch1("KEY")
ss.SortingviewWorkspaceSelection.insert1(key2, skip_duplicates=True)
ss.SortingviewWorkspace.populate(key2)
ss.SortingviewWorkspace().url(key2)

Versions are not the same. This might lead to errors. Use  spikeinterface version 0.95.0.dev0


OSError: Unable to create file (unable to open file: name = '/stelmo/nwb/recording/wilbur20210406_.nwb_02_r1_noPrePostTrialTimes_test_100s_25_default/recording.h5', errno = 13, error message = 'Permission denied', flags = 13, o_flags = 242)

## Second set of waveforms, metrics, autocuration

In [15]:
waveform_params_not_whitened='default_not_whitened'

waveforms_not_whitened = auto_curation_out_key.copy()
waveforms_not_whitened.update({'waveform_params_name': waveform_params_not_whitened})

ss.WaveformSelection.insert1(waveforms_not_whitened, skip_duplicates=True)
ss.Waveforms.populate([(ss.WaveformSelection & waveforms_not_whitened).proj()])
ss.Waveforms() & waveforms_not_whitened

Extracting waveforms...
Setting 'return_scaled' to False


/home/emonroe/miniconda2/envs/spyglass/lib/python3.8/multiprocessing/popen_fork.py:70: ResourceWarning: unclosed socket <zmq.Socket(zmq.PUSH) at 0x7f13f07d16a0>
  self.pid = os.fork()
/home/emonroe/miniconda2/envs/spyglass/lib/python3.8/multiprocessing/popen_fork.py:70: ResourceWarning: unclosed socket <zmq.Socket(zmq.PUSH) at 0x7f131cd45040>
  self.pid = os.fork()
/home/emonroe/miniconda2/envs/spyglass/lib/python3.8/multiprocessing/popen_fork.py:70: ResourceWarning: unclosed socket <zmq.Socket(zmq.PUSH) at 0x7f13f07d16a0>
  self.pid = os.fork()
/home/emonroe/miniconda2/envs/spyglass/lib/python3.8/multiprocessing/popen_fork.py:70: ResourceWarning: unclosed socket <zmq.Socket(zmq.PUSH) at 0x7f131cd45040>
  self.pid = os.fork()
/home/emonroe/miniconda2/envs/spyglass/lib/python3.8/multiprocessing/popen_fork.py:70: ResourceWarning: unclosed socket <zmq.Socket(zmq.PUSH) at 0x7f13f07d16a0>
  self.pid = os.fork()
/home/emonroe/miniconda2/envs/spyglass/lib/python3.8/multiprocessing/popen_fork.

Writing new NWB file senor20201030_40LSD389AI.nwb


/home/emonroe/miniconda2/envs/spyglass/lib/python3.8/site-packages/h5py/_hl/dataset.py:541: DeprecationWarning: Passing None into shape arguments as an alias for () is deprecated.
  arr = numpy.ndarray(selection.mshape, dtype=new_dtype)
/home/emonroe/miniconda2/envs/spyglass/lib/python3.8/site-packages/hdmf/build/objectmapper.py:256: DtypeConversionWarning: Spec 'Units/spike_times': Value with data type int64 is being converted to data type float64 as specified.
  warnings.warn(full_warning_msg, DtypeConversionWarning)
/home/emonroe/miniconda2/envs/spyglass/lib/python3.8/site-packages/datajoint/hash.py:39: ResourceWarning: unclosed file <_io.BufferedReader name='/stelmo/nwb/analysis/senor20201030_40LSD389AI.nwb'>
  return uuid_from_stream(Path(filepath).open("rb"), init_string=init_string)
/home/emonroe/miniconda2/envs/spyglass/lib/python3.8/site-packages/datajoint/external.py:276: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this w

*curation_id   *nwb_file_name *sort_group_id *sort_interval *preproc_param *team_name    *sorter        *sorter_params *artifact_remo *waveform_para waveform_extra analysis_file_ waveforms_obje
+------------+ +------------+ +------------+ +------------+ +------------+ +-----------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+
4              senor20201030_ 28             sleeps_runs_no default        ac_em_xs      mountainsort4  franklab_probe senor20201030_ default_not_wh /stelmo/nwb/wa senor20201030_ 9406bd98-3a98-
 (Total: 1)

In [16]:
metrics_params_not_whitened = 'EM_peak_offset_peak_chan'

metrics_key_not_whitened = waveforms_not_whitened.copy()
metrics_key_not_whitened['metric_params_name'] =  metrics_params_not_whitened

ss.MetricSelection.insert1(metrics_key_not_whitened, skip_duplicates=True)
ss.QualityMetrics.populate([(ss.MetricSelection & metrics_key_not_whitened).proj()])

Computed all metrics: {'peak_channel': {1: 256, 2: 256, 3: 256, 4: 257, 5: 257, 6: 258, 7: 259, 8: 259, 9: 259, 10: 259, 11: 260, 12: 260, 13: 260, 14: 260, 15: 260, 16: 261, 17: 260, 18: 261, 19: 262, 20: 260, 21: 263, 22: 263, 23: 264, 24: 264, 25: 267, 26: 263, 27: 265, 28: 266, 29: 267, 30: 267, 31: 267, 32: 267, 33: 267, 34: 267, 35: 268, 36: 268, 37: 268, 38: 267, 39: 268, 40: 268, 41: 269, 42: 269, 43: 269, 44: 267, 45: 270, 46: 270, 47: 267, 48: 271, 49: 271, 50: 272, 51: 271, 52: 271, 53: 272, 54: 272, 55: 272, 56: 272, 57: 272, 58: 272, 59: 272, 60: 273, 61: 273, 62: 274, 63: 275, 64: 275, 65: 275, 66: 276, 67: 277, 68: 277, 69: 277, 70: 277, 71: 278, 72: 278, 73: 278, 74: 278, 75: 278, 76: 278, 77: 278, 78: 279, 79: 279, 80: 279, 81: 279, 82: 279, 83: 280, 84: 280, 85: 280, 86: 281, 87: 281, 88: 281, 89: 281, 90: 281, 91: 281, 92: 281, 93: 282, 94: 282, 95: 282, 96: 282, 97: 282, 98: 282, 99: 282, 100: 282, 101: 282, 102: 283, 103: 283, 104: 283, 105: 283, 106: 284, 107: 285

/home/emonroe/miniconda2/envs/spyglass/lib/python3.8/site-packages/h5py/_hl/dataset.py:541: DeprecationWarning: Passing None into shape arguments as an alias for () is deprecated.
  arr = numpy.ndarray(selection.mshape, dtype=new_dtype)
/home/emonroe/miniconda2/envs/spyglass/lib/python3.8/site-packages/hdmf/spec/namespace.py:532: UserWarning: Ignoring cached namespace 'hdmf-common' version 1.5.0 because version 1.5.1 is already loaded.
  warn("Ignoring cached namespace '%s' version %s because version %s is already loaded."
/home/emonroe/miniconda2/envs/spyglass/lib/python3.8/site-packages/hdmf/spec/namespace.py:532: UserWarning: Ignoring cached namespace 'hdmf-experimental' version 0.1.0 because version 0.2.0 is already loaded.
  warn("Ignoring cached namespace '%s' version %s because version %s is already loaded."


Writing new NWB file senor20201030_JXZG06TY6R.nwb


/home/emonroe/miniconda2/envs/spyglass/lib/python3.8/site-packages/h5py/_hl/dataset.py:541: DeprecationWarning: Passing None into shape arguments as an alias for () is deprecated.
  arr = numpy.ndarray(selection.mshape, dtype=new_dtype)


Adding metric peak_channel : {1: 256, 2: 256, 3: 256, 4: 257, 5: 257, 6: 258, 7: 259, 8: 259, 9: 259, 10: 259, 11: 260, 12: 260, 13: 260, 14: 260, 15: 260, 16: 261, 17: 260, 18: 261, 19: 262, 20: 260, 21: 263, 22: 263, 23: 264, 24: 264, 25: 267, 26: 263, 27: 265, 28: 266, 29: 267, 30: 267, 31: 267, 32: 267, 33: 267, 34: 267, 35: 268, 36: 268, 37: 268, 38: 267, 39: 268, 40: 268, 41: 269, 42: 269, 43: 269, 44: 267, 45: 270, 46: 270, 47: 267, 48: 271, 49: 271, 50: 272, 51: 271, 52: 271, 53: 272, 54: 272, 55: 272, 56: 272, 57: 272, 58: 272, 59: 272, 60: 273, 61: 273, 62: 274, 63: 275, 64: 275, 65: 275, 66: 276, 67: 277, 68: 277, 69: 277, 70: 277, 71: 278, 72: 278, 73: 278, 74: 278, 75: 278, 76: 278, 77: 278, 78: 279, 79: 279, 80: 279, 81: 279, 82: 279, 83: 280, 84: 280, 85: 280, 86: 281, 87: 281, 88: 281, 89: 281, 90: 281, 91: 281, 92: 281, 93: 282, 94: 282, 95: 282, 96: 282, 97: 282, 98: 282, 99: 282, 100: 282, 101: 282, 102: 283, 103: 283, 104: 283, 105: 283, 106: 284, 107: 285, 108: 285

/home/emonroe/miniconda2/envs/spyglass/lib/python3.8/site-packages/datajoint/hash.py:39: ResourceWarning: unclosed file <_io.BufferedReader name='/stelmo/nwb/analysis/senor20201030_JXZG06TY6R.nwb'>
  return uuid_from_stream(Path(filepath).open("rb"), init_string=init_string)
/home/emonroe/miniconda2/envs/spyglass/lib/python3.8/site-packages/datajoint/external.py:276: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if check_hash:


In [17]:
ss.QualityMetrics & metrics_key_not_whitened

*curation_id   *nwb_file_name *sort_group_id *sort_interval *preproc_param *team_name    *sorter        *sorter_params *artifact_remo *waveform_para *metric_params quality_metric analysis_file_ object_id     
+------------+ +------------+ +------------+ +------------+ +------------+ +-----------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+
4              senor20201030_ 28             sleeps_runs_no default        ac_em_xs      mountainsort4  franklab_probe senor20201030_ default_not_wh EM_peak_offset /stelmo/nwb/wa senor20201030_ d4acf8ef-80c1-
 (Total: 1)

In [18]:
auto_curation_params_name_not_whitened = 'EM_peak_offset_pos'

autocuration_key_not_whitened = metrics_key_not_whitened.copy()
autocuration_key_not_whitened['auto_curation_params_name'] = auto_curation_params_name_not_whitened

ss.AutomaticCurationSelection.insert1(autocuration_key_not_whitened, skip_duplicates=True)
ss.AutomaticCuration.populate([(ss.AutomaticCurationSelection & autocuration_key_not_whitened).proj()])

In [19]:
ss.AutomaticCuration & autocuration_key_not_whitened

*curation_id   *nwb_file_name *sort_group_id *sort_interval *preproc_param *team_name    *sorter        *sorter_params *artifact_remo *waveform_para *metric_params *auto_curation auto_curat
+------------+ +------------+ +------------+ +------------+ +------------+ +-----------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +--------+
4              senor20201030_ 28             sleeps_runs_no default        ac_em_xs      mountainsort4  franklab_probe senor20201030_ default_not_wh EM_peak_offset EM_peak_offset =BLOB=    
 (Total: 1)

In [65]:
(ss.Curation & auto_curation_id2).fetch('quality_metrics')

array([{'peak_channel': {'1': 128, '2': 129, '3': 129, '4': 129, '5': 130, '6': 130, '7': 131, '8': 131, '9': 131, '10': 131, '11': 132, '12': 132, '13': 132, '14': 132, '15': 132, '16': 132, '17': 132, '18': 132, '19': 131, '20': 132, '21': 131, '22': 133, '23': 134, '24': 135, '25': 135, '26': 136, '27': 137, '28': 137, '29': 137, '30': 137, '31': 137, '32': 137, '33': 138, '34': 138, '35': 140, '36': 138, '37': 138, '38': 138, '39': 138, '40': 138, '41': 139, '42': 139, '43': 139, '44': 139, '45': 140, '46': 140, '47': 140, '48': 140, '49': 140, '50': 140, '51': 140, '52': 140, '53': 140, '54': 141, '55': 141, '56': 141, '57': 141, '58': 142, '59': 143, '60': 143, '61': 144, '62': 144, '63': 144, '64': 145, '65': 145, '66': 146, '67': 146, '68': 146, '69': 147, '70': 150, '71': 147, '72': 147, '73': 148, '74': 148, '75': 148, '76': 149, '77': 148, '78': 149, '79': 149, '80': 149, '81': 149, '82': 150, '83': 150, '84': 150, '85': 151, '86': 151, '87': 151, '88': 151, '89': 152, '90':

In [ ]:
auto_curation_id2 = (ss.AutomaticCuration & autocuration_key_not_whitened).fetch1('auto_curation_key')
key2  = (ss.Curation & auto_curation_id2).fetch1("KEY")
ss.SortingviewWorkspaceSelection.insert1(key2, skip_duplicates=True)
ss.SortingviewWorkspace.populate(key2)
ss.SortingviewWorkspace().url(key2)

In [67]:
# ss.SortingviewWorkspace()& key2

*curation_id   *nwb_file_name *sort_group_id *sort_interval *preproc_param *team_name    *sorter        *sorter_params *artifact_remo workspace_uri  sortingview_re sortingview_so channel      
+------------+ +------------+ +------------+ +------------+ +------------+ +-----------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +-----------+
2              senor20201030_ 24             sleeps_runs_no default        ac_em_xs      mountainsort4  franklab_probe senor20201030_ workspace://30 R-931ab86fd65a S-2e7d405cd836 franklab2    
 (Total: 1)

In [69]:
# ss.AutomaticCuration & autocuration_key_not_whitened

*curation_id   *nwb_file_name *sort_group_id *sort_interval *preproc_param *team_name    *sorter        *sorter_params *artifact_remo *waveform_para *metric_params *auto_curation auto_curat
+------------+ +------------+ +------------+ +------------+ +------------+ +-----------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +--------+
1              senor20201030_ 24             sleeps_runs_no default        ac_em_xs      mountainsort4  franklab_probe senor20201030_ default_not_wh EM_peak_offset EM_peak_offset =BLOB=    
 (Total: 1)

In [71]:
# ss.AutomaticCurationParameters.fetch()

array([('default', {}, {'nn_noise_overlap': ['>', 0.1, ['noise', 'reject']]}),
       ('EM_peak_offset', {}, {'peak_offset': ['<', -2, ['noise', 'reject']]}),
       ('EM_probe_autocuration_params', {}, {'nn_noise_overlap': ['>', 0.03, ['noise', 'reject']], 'isi_violation': ['>', 0.0025, ['noise', 'reject']], 'snr': ['<', 3, ['noise', 'reject']], 'nn_isolation': ['<', 0.95, ['noise', 'reject']]}),
       ('JG_DG_AutoCuration_params', {}, {'nn_noise_overlap': ['>', 0.03, ['noise', 'reject']], 'isi_violation': ['>', 0.0025, ['noise', 'reject']]}),
       ('mike_noise_isi_isolation', {}, {'nn_noise_overlap': ['>', 0.1, ['noise', 'reject']], 'isi_violation': ['>', 0.01, ['noise', 'reject']], 'nn_isolation': ['<', 0.95, ['noise', 'reject']]}),
       ('mike_noise_isi_isolation_09', {}, {'nn_noise_overlap': ['>', 0.1, ['noise', 'reject']], 'isi_violation': ['>', 0.01, ['noise', 'reject']], 'nn_isolation': ['<', 0.9, ['noise', 'reject']]}),
       ('none', {}, {})],
      dtype=[('auto_curati

## Manual curation

In [116]:
# (ss.SortingviewWorkspace & autocuration_key).fetch1('workspace_uri')

DataJointError: fetch1 should only return one tuple. 0 tuples found

### Can add your own labels to the URL from above 

In [117]:
# manual_curation_key = ss.SortingviewWorkspace().insert_manual_curation(key, 'manually curated')

{'curation_id': 1, 'nwb_file_name': 'senor20201030_.nwb', 'sort_group_id': 31, 'sort_interval_name': 'sleeps_runs_noPrePostTrialTimes raw data valid times', 'preproc_params_name': 'default', 'team_name': 'ac_em_xs', 'sorter': 'mountainsort4', 'sorter_params_name': 'franklab_probe_ctx_30KHz', 'artifact_removed_interval_list_name': 'senor20201030_.nwb_sleeps_runs_noPrePostTrialTimes raw data valid times_31_default_ampl_2000_z_30_prop_075_1ms_artifact_removed_valid_times'}


In [ ]:
# (ss.Curation() & {'nwb_file_name': 'senor20201030_.nwb','sort_group_id':31}).fetch('curation_labels')
                                                                        

In [20]:
# #when youre ready to add everything into the final curated tables to look at units, uncomment these 

# final_curation_temp_key = (ss.AutomaticCuration & autocuration_key).fetch1('auto_curation_key')
# final_curation_key = (ss.Curation & final_curation_temp_key).fetch1("KEY")
# final_curation_key
# ss.CuratedSpikeSortingSelection.insert1(final_curation_key, skip_duplicates=True)
# ss.CuratedSpikeSorting.populate(final_curation_key)
# ss.Curation() & final_curation_key

Found 9 accepted units


/home/emonroe/miniconda2/envs/spyglass/lib/python3.8/site-packages/h5py/_hl/dataset.py:541: DeprecationWarning: Passing None into shape arguments as an alias for () is deprecated.
  arr = numpy.ndarray(selection.mshape, dtype=new_dtype)
/home/emonroe/miniconda2/envs/spyglass/lib/python3.8/site-packages/hdmf/spec/namespace.py:532: UserWarning: Ignoring cached namespace 'hdmf-common' version 1.5.0 because version 1.5.1 is already loaded.
  warn("Ignoring cached namespace '%s' version %s because version %s is already loaded."
/home/emonroe/miniconda2/envs/spyglass/lib/python3.8/site-packages/hdmf/spec/namespace.py:532: UserWarning: Ignoring cached namespace 'hdmf-experimental' version 0.1.0 because version 0.2.0 is already loaded.
  warn("Ignoring cached namespace '%s' version %s because version %s is already loaded."


Writing new NWB file senor20201030_5CU1BOAZ08.nwb


/home/emonroe/miniconda2/envs/spyglass/lib/python3.8/site-packages/h5py/_hl/dataset.py:541: DeprecationWarning: Passing None into shape arguments as an alias for () is deprecated.
  arr = numpy.ndarray(selection.mshape, dtype=new_dtype)


Adding metric snr : [39.98102692 57.30613858 10.54637818  9.22808091 18.35277761 23.24685164
 33.03499969 23.24685164 23.24685164]
Adding metric isi_violation : [0.         0.00489663 0.00208773 0.00767123 0.         0.
 0.00010224 0.         0.        ]
Adding metric nn_isolation : [0.98931789 0.9867     0.9725     0.9706     0.9923     0.9897
 0.9896     0.99235474 0.9899    ]
Adding metric nn_noise_overlap : [0.0003861  0.         0.0052     0.0195     0.0006     0.0002
 0.         0.00030581 0.0005    ]


/home/emonroe/miniconda2/envs/spyglass/lib/python3.8/site-packages/datajoint/hash.py:39: ResourceWarning: unclosed file <_io.BufferedReader name='/stelmo/nwb/analysis/senor20201030_5CU1BOAZ08.nwb'>
  return uuid_from_stream(Path(filepath).open("rb"), init_string=init_string)
/home/emonroe/miniconda2/envs/spyglass/lib/python3.8/site-packages/datajoint/external.py:276: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if check_hash:


NameError: name 'auto_curation_out_key' is not defined

In [21]:
# CuratedSpikeSorting().Unit & final_curation_key

*curation_id   *nwb_file_name *sort_group_id *sort_interval *preproc_param *team_name    *sorter        *sorter_params *artifact_remo *unit_id    label     nn_noise_overl nn_isolation   isi_violation  snr         firing_rate    num_spikes     peak_channel  
+------------+ +------------+ +------------+ +------------+ +------------+ +-----------+ +------------+ +------------+ +------------+ +---------+ +-------+ +------------+ +------------+ +------------+ +---------+ +------------+ +------------+ +------------+
1              senor20201030_ 8              runs_noPrePost franklab_tetro ac_em_xs      mountainsort4  franklab_tetro senor20201030_ 2                     0.0003861      0.989318       0.0            39.981      -1.0           -1             None          
1              senor20201030_ 8              runs_noPrePost franklab_tetro ac_em_xs      mountainsort4  franklab_tetro senor20201030_ 4                     0.0            0.9867         0.00489663     57.3061     -1.0           -1             None          
1              senor20201030_ 8              runs_noPrePost franklab_tetro ac_em_xs      mountainsort4  franklab_tetro senor20201030_ 11                    0.0052         0.9725         0.00208773     10.5464     -1.0           -1             None          
1              senor20201030_ 8              runs_noPrePost franklab_tetro ac_em_xs      mountainsort4  franklab_tetro senor20201030_ 12                    0.0195         0.9706         0.00767123     9.22808     -1.0           -1             None          
1              senor20201030_ 8              runs_noPrePost franklab_tetro ac_em_xs      mountainsort4  franklab_tetro senor20201030_ 13                    0.0006         0.9923         0.0            18.3528     -1.0           -1             None          
1              senor20201030_ 8              runs_noPrePost franklab_tetro ac_em_xs      mountainsort4  franklab_tetro senor20201030_ 15                    0.0002         0.9897         0.0            23.2469     -1.0           -1             None          
1              senor20201030_ 8              runs_noPrePost franklab_tetro ac_em_xs      mountainsort4  franklab_tetro senor20201030_ 16                    0.0            0.9896         0.000102239    33.035      -1.0           -1             None          
1              senor20201030_ 8              runs_noPrePost franklab_tetro ac_em_xs      mountainsort4  franklab_tetro senor20201030_ 17                    0.00030581     0.992355       0.0            23.2469     -1.0           -1             None          
1              senor20201030_ 8              runs_noPrePost franklab_tetro ac_em_xs      mountainsort4  franklab_tetro senor20201030_ 18                    0.0005         0.9899         0.0            23.2469     -1.0           -1             None          
 (Total: 9)

In [ ]:
# if i merge, then autocurate again. 

In [ ]:
#not quite sure if we should add these right away or if we should wait until after some manual curation. 
# final_curation_temp_key = (ss.AutomaticCuration & autocuration_key).fetch1('auto_curation_key')
# final_curation_key = (ss.Curation & final_curation_temp_key).fetch1("KEY")

# ss.CuratedSpikeSortingSelection.insert1(final_curation_key, skip_duplicates=True)
# ss.CuratedSpikeSorting.populate(final_curation_key)
# ss.Curation() & auto_curation_out_key
#should only do this in the end 
#if i delete from curation, things will be left. actually maybe not. if i delete 0, it should delte everything else. 
#look at whats left. 